mod_13/django_proj/books/books/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls", namespace="users")),
]

mod_13/django_proj/books/quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="main"),
    path("page/<int:page>/", views.main, name="main"),
    path("author/add", views.add_author, name="add_author"),
    path("author/<str:question_id>", views.author, name="author"),
    path("tag/<str:tag_name>/page/<int:page>/", views.find_by_tag, name="find_by_tag"),
    path("tag/", views.tag, name="tag"),
    path("add/", views.add_quote, name="add_quote"),
]

mod_13/django_proj/books/users/urls.py
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.signupuser, name="signup"),
    path("login/", views.loginuser, name="login"),
    path("logout/", views.logoutuser, name="logout"),
    # path("profile/", views.profile, name="profile"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

mod_13/django_proj/books/quotes/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=120)
    slug = models.CharField(max_length=120, unique=True)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()

    def __str__(self) -> str:
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=40, unique=True)

    def __str__(self) -> str:
        return self.tag


class Quote(models.Model):
    quote = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.DO_NOTHING)
    tags = models.ManyToManyField(Tag)

    def __str__(self) -> str:
        return f"{self.quote[:45]} ..."

mod_13/django_proj/books/quotes/forms.py
from .models import Tag, Quote, Author
from django.forms import (
    ModelForm,
    CharField,
    TextInput,
    MultiValueField,
    Textarea,
    ModelChoiceField,
    Select,
)


class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=45, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ["name"]


class AddAuthorForm(ModelForm):

    fullname = CharField(
        min_length=3, max_length=120, required=True, widget=TextInput()
    )
    born_date = CharField(min_length=3, max_length=50, widget=TextInput())
    born_location = CharField(min_length=3, max_length=150, widget=TextInput())
    description = CharField(min_length=3, required=True, widget=Textarea())

    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]


class AddQuoteForm(ModelForm):
    quote = CharField(
        min_length=3, required=True, widget=Textarea(attrs={"class": "form-control"})
    )
    author = ModelChoiceField(
        queryset=(Author.objects.order_by("fullname").all()),
        required=True,
        widget=Select(attrs={"class": "form-control"}),
    )

    class Meta:
        model = Quote
        fields = ["quote", "author"]
        exclude = ["tags"]

mod_13/django_proj/books/quotes/views.py
from collections import Counter, defaultdict

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template import loader

from .forms import AddAuthorForm, AddQuoteForm, TagForm
from .models import Author, Quote, Tag


def main(request, page=1):
    latest_quotes_list = Quote.objects.all()
    paginator = Paginator(latest_quotes_list, 5)
    cur_page = paginator.page(page)
    template = loader.get_template("quotes/quotes.html")
    context = {
        "latest_quotes_list": cur_page.object_list,
        "top10tags": top10tags(),
        "page": {
            "previous": cur_page.previous_page_number() if page > 1 else False,
            "next": cur_page.next_page_number() if cur_page.has_next() else False,
        },
    }
    return HttpResponse(template.render(context, request))


def author(request, question_id):
    template = loader.get_template("quotes/author.html")
    context = {}
    return HttpResponse(template.render(request=request))


def find_by_tag(request, tag_name, page=1):
    tag = Tag.objects.get(name=tag_name)
    quotes_by_tag = Quote.objects.filter(tags__id=tag.id)
    paginator = Paginator(quotes_by_tag, 5)
    cur_page = paginator.page(page)

    template = loader.get_template("quotes/quotes_by_tag.html")
    context = {
        "tag": tag,
        "latest_quotes_list": quotes_by_tag,
        "top10tags": top10tags(),
        "page": {
            "previous": cur_page.previous_page_number() if page > 1 else False,
            "next": cur_page.next_page_number() if cur_page.has_next() else False,
        },
    }
    return HttpResponse(template.render(context, request))


@login_required
def tag(request):
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotes:main")
        else:
            return render(request, "quotes/tag.html", {"form": form})

    return render(request, "quotes/tag.html", {"form": TagForm()})


@login_required
def add_author(request):
    if request.method == "POST":
        form = AddAuthorForm(request.POST)
        if form.is_valid():
            new_author = form.save()
            new_author.slug = get_slug(new_author.fullname)
            new_author.save()
            return redirect(to="quotes:main")
        else:
            return render(request, "quotes/add_author.html", {"form": form})

    return render(request, "quotes/add_author.html", {"form": AddAuthorForm()})


def get_slug(data):
    return data.strip().replace(" ", "-")


@login_required
def add_quote(request):
    authors = Author.objects.order_by("fullname").all()
    tags = Tag.objects.order_by("name").all()
    if request.method == "POST":
        form = AddQuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist("tags"))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            return redirect(to="quotes:main")
        else:
            return render(
                request,
                "quotes/add_quote.html",
                {"authors": authors, "tags": tags, "form": form},
            )

    return render(
        request,
        "quotes/add_quote.html",
        {"authors": authors, "tags": tags, "form": AddQuoteForm()},
    )


def top10tags():
    font_siza = [28, 26, 24, 22, 20, 18, 16, 14, 12, 10]
    quotes = Quote.objects.all()
    tag_frequency = defaultdict(int)
    for quote in quotes:
        for tag in quote.tags.all():
            tag_frequency[tag.name] += 1

    top10tupl = Counter(tag_frequency).most_common()[:10]
    top10tags = [t[0] for t in top10tupl]
    zip(top10tags, font_siza)
    return [{"tag": t[0], "size": t[1]} for t in zip(top10tags, font_siza)]

mod_13/django_proj/books/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}
<div style="margin-bottom: 30px; border-bottom: 2px solid; padding-left: 30px; padding-bottom: 20px">
    <a class="btn btn-info" href="/" role="button"> Go back to the main page </a>
</div>

<form method="POST" action="{% url 'quotes:add_author' %}" class="form-horizontal">
    {% csrf_token %}
    <div class="form-group">
        <label class="col-sm-2">
            Enter author full name:
        </label>
        <div class="col-sm-8">
            {{ form.fullname }}
            <span>{{ form.errors.fullname }}</span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2">
            Enter birthday:
        </label>
        <div class="col-sm-8">
            {{ form.born_date }}
            <span>{{ form.errors.born_date }}</span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2">
            Enter born place:
        </label>
        <div class="col-sm-8">
            {{ form.born_location }}
            <span>{{ form.errors.born_location }}</span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2">
            Enter description:
        </label>
        <div class="col-sm-8">
            {{ form.description }}
            <span>{{ form.errors.description }}</span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Submit</button>
            <button type="reset" class="btn btn-default">Reset</button>
        </div>
    </div>
</form>

{% endblock %}

mod_13/django_proj/books/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}

<div class="row">
    <div class="col-md-8">

        <div style="margin-bottom: 30px; border-bottom: 2px solid; padding-left: 30px; padding-bottom: 20px">
            <a class="btn btn-info" href="/" role="button"> Go back to the main page </a>
            <a class="btn btn-info" href="{% url 'quotes:add_author' %}" role="button"> Add author </a>
            <a class="btn btn-info" href="{% url 'quotes:tag' %}" role="button"> Add tag </a>
        </div>

        <form method="POST" action="{% url 'quotes:add_quote' %}" class="form-horizontal">
            {% csrf_token %}
            <div class="form-group">
                <label class="col-sm-2">
                    Enter the quote:
                </label>
                <div class="col-sm-10">
                    {{ form.quote }}
                    <span>{{ form.errors.quote }}</span>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2">
                    Select author:
                </label>
                <div class="col-sm-6">
                    {{ form.author }}
                    <span>{{ form.errors.auhtor }}</span>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2">
                    Select tags:
                </label>
                <div class="col-sm-6">
                    <select name="tags" multiple="multiple" size="6" class="form-control" required>
                        {% for tag in tags %}
                        <option value="{{tag.name}}">{{tag.name}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <button type="reset" class="btn btn-default">Reset</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

mod_13/django_proj/books/quotes/templates/quotes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Quotes to Scrape</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
</head>

<body>
    <div class="container">
        <div class="row header-box">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                {% if user.is_authenticated %}
                <p>
                    Welcome <b>{{ user.username }}!</b>
                </p>
                <p>
                    <a href="{% url 'users:logout' %}" role="button">Logout</a>
                </p>
                {% else %}
                <p><a href="{% url 'users:signup' %}" role="button">Sign Up</a></p>
                <p><a href="{% url 'users:login' %}" role="button">Login</a></p>
                {% endif %}
            </div>
        </div>

        {% block content %} {% endblock %}

    </div>

</body>
</html>

mod_13/django_proj/books/quotes/templates/quotes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Quotes to Scrape</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
</head>
<body>
<main class="container">
    <h1>Main page</h1>
</main>
</body>
</html>

mod_13/django_proj/books/quotes/templates/quotes/quotes.html
{% extends "quotes/base.html" %}

{% block content %}

<div class="row">
    <div class="col-md-8">
        <div style="margin-bottom: 30px; border-bottom: 2px solid; padding-left: 30px; padding-bottom: 20px">
            {% if user.is_authenticated %}
            <a class="btn btn-info" href="{% url 'quotes:add_quote' %}" role="button"> Add quote </a>
            {% endif %}
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-8">

        {% if latest_quotes_list %}
        {% for quote in latest_quotes_list %}
        <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{ quote.quote }}</span>
            <span>by <small class="author" itemprop="author">{{ quote.author }}</small>
                <a href="/author/{{ quote.author.slug }}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                <meta class="keywords" itemprop="keywords" content="change,deep-thoughts,thinking,world" />
                {% for tag in quote.tags.all %}
                <a class="tag" href="/tag/{{ tag.name }}/page/1/">{{ tag.name }}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}

        {% else %}
        <p>No quotes are available.</p>
        {% endif %}

        <nav>
            <ul class="pager">
                {% if page.previous %}
                <li class="previous">
                    <a href="/page/{{ page.previous }}/"><span aria-hidden="true">&larr;</span> Previous</a>
                </li>
                {% endif %}

                {% if page.next %}
                <li class="next">
                    <a href="/page/{{ page.next }}/">Next <span aria-hidden="true">&rarr;</span></a>
                </li>
                {% endif %}

            </ul>
        </nav>
    </div>
    <div class="col-md-4 tags-box">

        <h2>Top Ten tags</h2>
        {% for tag in top10tags %}
        <span class="tag-item">
            <a class="tag" style="font-size: {{ tag.size }}px" href="/tag/{{ tag.tag }}/page/1/">{{ tag.tag }}</a>
        </span>
        {% endfor %}

    </div>
</div>

{% endblock %}

mod_13/django_proj/books/quotes/templates/quotes/quotes_by_tag.html
{% extends "quotes/base.html" %}

{% block content %}

<div style="margin-bottom: 30px; border-bottom: 2px solid; padding-left: 30px; padding-bottom: 20px">
    {% if user.is_authenticated %}
    <a class="btn btn-info" href="{% url 'quotes:add_quote' %}" role="button"> Add quote </a>
    {% endif %}
</div>
<h3>Viewing tag:
    <a href="/tag/{{ tag.name }}/page/1/">life</a>
</h3>
<div class="row">
    <div class="col-md-8">

        {% if latest_quotes_list %}
        {% for quote in latest_quotes_list %}
        <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{ quote.quote }}</span>
            <span>by <small class="author" itemprop="author">{{ quote.author }}</small>
                <a href="/author/{{ quote.author.slug }}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                <meta class="keywords" itemprop="keywords" content="change,deep-thoughts,thinking,world" />
                {% for tag in quote.tags.all %}
                <a class="tag" href="/tag/{{ tag.name }}/page/1/">{{ tag.name }}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}

        {% else %}
        <p>No quotes are available.</p>
        {% endif %}

        <nav>
            <ul class="pager">
                {% if page.previous %}
                <li class="previous">
                    <a href="/page/{{ page.previous }}/"><span aria-hidden="true">&larr;</span> Previous</a>
                </li>
                {% endif %}

                {% if page.next %}
                <li class="next">
                    <a href="/page/{{ page.next }}/">Next <span aria-hidden="true">&rarr;</span></a>
                </li>
                {% endif %}

            </ul>
        </nav>
    </div>
    <div class="col-md-4 tags-box">

        <h2>Top Ten tags</h2>
        {% for tag in top10tags %}
        <span class="tag-item">
            <a class="tag" style="font-size: {{ tag.size }}px" href="/tag/{{ tag.tag }}/page/1/">{{ tag.tag }}</a>
        </span>
        {% endfor %}

    </div>
</div>

{% endblock %}

mod_13/django_proj/books/quotes/templates/quotes/tag.html
{% extends "quotes/base.html" %}

{% block content %}
<div style="margin-bottom: 30px; border-bottom: 2px solid; padding-left: 30px; padding-bottom: 20px">
    <a class="btn btn-info" href="/" role="button"> Go back to the main page </a>
</div>

<form method="POST" action="{% url 'quotes:tag' %}" class="form-horizontal">
    {% csrf_token %}
    <div class="form-group">
        <label class="col-sm-2">Enter the tag name:
        </label>
        <div class="col-sm-8">
            {{form.name}}
            <span>{{ form.errors.quote }}</span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">Save</button>
            <button type="reset" class="btn btn-default">Reset</button>
        </div>
    </div>
</form>

{% endblock %}

mod_13/django_proj/books/quotes/templates/quotes/top_ten_tags.html
{% extends "noteapp/index.html" %}

{% block content %}

<h2>Top Ten tags</h2>

{% for tag in tags %}
<span class="tag-item">
    <a class="tag" style="font-size: 28px" href="/tag/love/">love</a>
</span>
{% endfor %}

{% endblock %}